(()=>{'use strict';
const API='https://zrjxlbkbctlapgupktxw.supabase.co/functions/v1/manage-discord-bot',KEY='sb_publishable_LfngX7pwFruPw35_ZUdO4Q_MGAHoeW0',APP='1531023771211792384',CACHE_TTL=60000;
const token=()=>sessionStorage.getItem('discovery_access_token')||sessionStorage.getItem('discord_bot_admin_token')||'';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function call(body){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',apikey:KEY},body:JSON.stringify({...body,access_token:token(),application_id:APP,view_scope:'personal'}),signal:controller.signal});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Datele nu au putut fi încărcate.');return d}catch(error){if(error?.name==='AbortError')throw Error('Conexiunea durează prea mult. Reîncarcă pagina și încearcă din nou.');throw error}finally{clearTimeout(timeout)}}
const $=id=>document.getElementById(id),status=(m,k='')=>{$('status').textContent=m;$('status').className=`status ${k}`};
const cacheKey=(kind,guild)=>`panel-pro-${token().slice(-12)}-${kind}-${guild}`,readCache=(kind,guild)=>{try{const item=JSON.parse(sessionStorage.getItem(cacheKey(kind,guild))||'null');return item&&Date.now()-item.time<CACHE_TTL?item.value:null}catch(_){return null}},writeCache=(kind,guild,value)=>{try{sessionStorage.setItem(cacheKey(kind,guild),JSON.stringify({time:Date.now(),value}))}catch(_){} };
function moduleLink(key,guild){const pages={pontaj:'pontaj.html',requests_departments:'invoiri-angajati.html',requests_organization:'invoiri-organizatie.html',weekly_reports:'rapoarte.html',organization:'anunturi-organizatie.html',departments:'anunturi-angajati.html',contracts:'contracte.html',event_reminders:'evenimente.html',marketplace:'marketplace.html',stash:'stash.html',actions_organization:'actiuni.html'};return pages[key]?pages[key]+'?guild_id='+encodeURIComponent(guild):'module-dashboard.html?module='+encodeURIComponent(key)+'&guild_id='+encodeURIComponent(guild)}
function paint(overview,guild){
  $('guild-title').textContent=overview.guild_name||guild.name;
  $('guild-copy').textContent=`${overview.plan==='premium'?'Premium activ':overview.plan==='trial'?'Trial activ':'Plan gratuit'} · modulele sunt filtrate după abonament și rolurile Discord configurate.`;
  const modules=(overview.modules||[]).filter(m=>m.active!==false);
  const linkFor=m=>moduleLink(m.key,guild.id);
  const nav=$('module-nav');
  if(nav){const primary=modules.slice(0,8),extra=modules.slice(8);nav.innerHTML='<a class="active" href="dashboard.html">Dashboard</a>'+primary.map(m=>'<a href="'+linkFor(m)+'">'+esc(m.label)+'</a>').join('')+(extra.length?'<details class="nav-more"><summary>Mai multe module ('+extra.length+')</summary>'+extra.map(m=>'<a href="'+linkFor(m)+'">'+esc(m.label)+'</a>').join('')+'</details>':'')}
  const card=m=>`<article class="module"><span class="badge ${m.premium?'premium':''}">${m.premium?'⭐ Premium':'✓ Gratuit'}</span><h3>${esc(m.label)}</h3><p>${esc(m.key==='weekly_reports'?'Rapoarte pontaj și status live într-o singură pagină.':m.key==='pontaj'?'Pontaje și ture pentru membrii serverului.':m.key==='requests_departments'?'Învoiri pentru angajați.':m.description||'Controlează modulul Panel Pro din web.')}</p><a class="module-open" href="${linkFor(m)}">Deschide modul <span aria-hidden="true">→</span></a></article>`;
  const primaryCards=modules.slice(0,6),extraCards=modules.slice(6);
  $('modules').innerHTML=(primaryCards.map(card).join('')||'<div class="empty">Nu există module disponibile pentru acest server.</div>')+(extraCards.length?'<details class="modules-more"><summary>Arată celelalte module ('+extraCards.length+')</summary><div class="modules-more-grid">'+extraCards.map(card).join('')+'</div></details>':'');
}
async function load(){try{status('Se verifică accesul…');let bootstrap=readCache('bootstrap','current');if(!bootstrap){bootstrap=await call({action:'bootstrap'});writeCache('bootstrap','current',bootstrap)}const guilds=bootstrap.guilds||[];if(!guilds.length)throw Error('Nu ai acces la niciun server Panel Pro.');const select=$('guild-select');select.innerHTML=guilds.map(g=>`<option value="${esc(g.id)}">${esc(g.name)} · ${esc(g.plan==='premium'?'Premium':g.plan==='trial'?'Trial':'Free')}</option>`).join('');const stored=sessionStorage.getItem('panel_pro_selected_guild');if(stored&&guilds.some(g=>String(g.id)===stored))select.value=stored;let loading=0;const render=async()=>{const guild=guilds.find(g=>String(g.id)===String(select.value))||guilds[0];sessionStorage.setItem('panel_pro_selected_guild',guild.id);const cached=readCache('catalog',guild.id);if(cached){paint(cached,guild);status(`Server selectat: ${guild.name} · se verifică actualizările…`,'ok')}else{$('modules').innerHTML='<div class="empty">Se încarcă modulele…</div>'}const request=++loading;try{const overview=await call({action:'module_catalog',guild_id:guild.id});if(request!==loading)return;writeCache('catalog',guild.id,overview);paint(overview,guild);status(`Server selectat: ${guild.name}`,'ok')}catch(e){if(!cached)throw e}};select.onchange=render;await render()}catch(e){status(e.message,'error');$('modules').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}load()})();