(() => {
  'use strict';
  const API = 'https://zrjxlbkbctlapgupktxw.supabase.co/functions/v1/manage-discord-bot';
  const KEY = 'sb_publishable_LfngX7pwFruPw35_ZUdO4Q_MGAHoeW0';
  const APP = '1531023771211792384';
  const token = () => sessionStorage.getItem('discovery_access_token') || sessionStorage.getItem('discord_bot_admin_token') || '';
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const call = async (guildId) => {
    const response = await fetch(API, { method: 'POST', headers: { 'Content-Type': 'application/json', apikey: KEY }, body: JSON.stringify({ action: 'dashboard_overview', guild_id: guildId, view_scope: 'personal', access_token: token(), application_id: APP }) });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(data.error || 'Statusul configurării nu a putut fi verificat.');
    return data;
  };
  const style = document.createElement('style');
  style.textContent = '.onboarding{margin-top:12px;padding:14px;border:1px solid #2c5270;border-radius:14px;background:linear-gradient(145deg,#0d2237,#081322);font-size:11px}.onboarding-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.onboarding h3{margin:0;font-size:14px;color:#e0f2fe}.onboarding p{margin:5px 0;color:#9fb0c5;line-height:1.45}.onboarding-plan{margin:8px 0;padding:8px;border:1px solid #36516f;border-radius:8px;color:#bae6fd;background:#082238}.onboarding-progress{height:7px;margin:10px 0;border-radius:99px;background:#16283e;overflow:hidden}.onboarding-progress i{display:block;height:100%;background:#22d3ee;border-radius:99px}.onboarding-steps{display:grid;gap:6px;margin:10px 0}.onboarding-step{display:flex;gap:8px;align-items:flex-start;padding:8px;border:1px solid #263b58;border-radius:9px;background:#0b1729}.onboarding-step strong{display:block;color:#e2e8f0}.onboarding-step small{display:block;color:#94a3b8;margin-top:2px}.onboarding-step.done{border-color:#166534;background:#082516}.onboarding-step.warn{border-color:#92400e;background:#2a1806}.onboarding-actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}.onboarding .button{padding:8px 10px;font-size:10px}.onboarding-critical{color:#fecaca!important}.onboarding details{margin-top:8px;color:#cbd5e1}.onboarding summary{cursor:pointer;font-weight:800}@media(max-width:700px){.onboarding-head{flex-direction:column}}';
  document.head.appendChild(style);
  const step = (ok, title, help) => `<div class="onboarding-step ${ok ? 'done' : 'warn'}"><span>${ok ? '✅' : '⚠️'}</span><div><strong>${esc(title)}</strong><small>${esc(help)}</small></div></div>`;
  const render = (card, data) => {
    let panel = card.querySelector('.onboarding');
    if (!panel) { panel = document.createElement('section'); panel.className = 'onboarding'; const overview = card.querySelector('.server-overview'); (overview || card).appendChild(panel); }
    const id = card.dataset.guildId;
    const admin = data.bot?.administrator === true;
    const rolePosition = data.bot?.role_position_ok !== false;
    const online = data.bot?.online === true;
    const channels = Number(data.channels?.total || 0) > 0 && !data.channels?.error;
    const configured = (data.modules || []).filter((m) => m.embed_configured).length > 0;
    const active = (data.modules || []).filter((m) => m.active !== false && m.enabled !== false && m.embed_configured).length > 0;
    const plan = data.subscription?.plan || 'free';
    const premiumModules = (data.modules || []).filter((m) => m.premium === true);
    const lockedPremium = plan === 'free' ? premiumModules.filter((m) => !m.embed_configured || m.enabled === false).length : 0;
    const done = [online, admin, rolePosition, channels, configured, active].filter(Boolean).length;
    panel.innerHTML = `<div class="onboarding-head"><div><h3>🚀 Tutorial de instalare Panel Pro</h3><p>Urmează pașii de mai jos. Botul trebuie să aibă permisiunea <b>Administrator</b> pentru a funcționa complet.</p></div><button type="button" class="button" data-onboarding-hide>${done === 6 ? 'Ascunde tutorialul' : 'Închide'}</button></div><div class="onboarding-progress"><i style="width:${Math.round(done / 6 * 100)}%"></i></div><p><b>${done}/6 pași finalizați</b></p><div class="onboarding-plan"><b>Abonament: ${esc(plan === 'premium' ? 'Premium' : plan === 'trial' ? 'Trial activ' : 'Free')}</b> · ${plan === 'free' ? `${premiumModules.length} module Premium sunt disponibile după activarea Premium${lockedPremium ? `; ${lockedPremium} nu sunt configurate` : ''}.` : 'Toate modulele Premium sunt disponibile.'}</div><div class="onboarding-steps">${step(online, 'Botul este online', online ? 'Conexiunea cu Discord este activă.' : 'Verifică dacă botul este instalat pe server.')}${step(admin, 'Botul are Administrator', admin ? 'Permisiunea este activă.' : 'Reinstalează botul și bifează Administrator la permisiuni.')}${step(rolePosition, 'Rolul botului este valid', rolePosition ? 'Rolul botului poate funcționa corect pe server.' : 'Mută rolul botului mai sus în lista de roluri Discord.')}${step(channels, 'Canalele Discord sunt accesibile', channels ? `${data.channels.total} canale pot fi folosite.` : 'Botul nu poate vedea canalele serverului.')}${step(configured, 'Canalele modulelor sunt configurate', configured ? 'Cel puțin un modul are canal configurat.' : 'Apasă configurarea automată pentru a crea și lega canalele.')}${step(active, 'Modulele sunt active', active ? 'Poți folosi modulele configurate.' : 'Activează modulele după ce alegi canalele.')}</div><div class="onboarding-actions"><button type="button" class="button primary" data-onboarding-auto>⚙️ Configurează automat canalele</button><button type="button" class="button" data-onboarding-test>🧪 Rulează testul final</button><button type="button" class="button" data-onboarding-diagnostic>📋 Copiază diagnosticul</button><button type="button" class="button" data-onboarding-reset>↺ Resetează rutele</button><a class="button cyan" href="configurare-server.html?guild_id=${encodeURIComponent(id)}">🧩 Configurează modulele</a>${!admin ? `<a class="button" target="_blank" rel="noreferrer" href="https://discord.com/oauth2/authorize?client_id=${APP}&scope=bot%20applications.commands&permissions=8&guild_id=${encodeURIComponent(id)}">🔐 Reinstalează cu Administrator</a>` : ''}</div><details><summary>Ce permisiuni sunt necesare?</summary><p>Administrator include vizualizarea canalelor, trimiterea mesajelor, embeduri, gestionarea mesajelor și funcțiile de log. Activează și Server Members Intent și Message Content Intent în Discord Developer Portal.</p></details>${data.bot?.missing_permissions?.length ? `<p class="onboarding-critical">Permisiuni lipsă: ${esc(data.bot.missing_permissions.join(', '))}</p>` : ''}`;
    panel.querySelector('[data-onboarding-hide]').onclick = () => { panel.hidden = true; localStorage.setItem(`panel-pro-onboarding-${id}`, 'hidden'); };
    panel.querySelector('[data-onboarding-auto]').onclick = async (event) => { const button = event.currentTarget; button.disabled = true; button.textContent = 'Se configurează…'; try { await fetch(API, { method: 'POST', headers: { 'Content-Type': 'application/json', apikey: KEY }, body: JSON.stringify({ action: 'auto_configure_guild', guild_id: id, view_scope: 'personal', access_token: token(), application_id: APP }) }); render(card, await call(id)); } catch (error) { button.disabled = false; button.textContent = error.message; } };
    panel.querySelector('[data-onboarding-test]').onclick = async (event) => { const button = event.currentTarget; button.disabled = true; button.textContent = 'Se testează…'; try { const response = await fetch(API, { method: 'POST', headers: { 'Content-Type': 'application/json', apikey: KEY }, body: JSON.stringify({ action: 'test_setup', guild_id: id, view_scope: 'personal', access_token: token(), application_id: APP }) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || 'Testul nu a putut fi finalizat.'); button.textContent = `✅ ${result.message || 'Test finalizat'}`; } catch (error) { button.disabled = false; button.textContent = `⚠️ ${error.message}`; } };
    panel.querySelector('[data-onboarding-diagnostic]').onclick = async (event) => { const button = event.currentTarget; const text = `Panel Pro diagnostic\nServer: ${card.querySelector('h2')?.textContent || id}\nGuild ID: ${id}\nBot online: ${online ? 'DA' : 'NU'}\nAdministrator: ${admin ? 'DA' : 'NU'}\nRol valid: ${rolePosition ? 'DA' : 'NU'}\nCanale: ${data.channels?.total || 0}\nPermisiuni lipsă: ${(data.bot?.missing_permissions || []).join(', ') || 'niciuna'}`; try { await navigator.clipboard.writeText(text); button.textContent = '✅ Diagnosticul a fost copiat'; } catch (_) { button.textContent = 'Selectează și copiază manual'; } };
    panel.querySelector('[data-onboarding-reset]').onclick = async (event) => { if (!confirm('Resetezi rutele canalelor? Embedurile existente nu vor fi șterse din Discord.')) return; const button = event.currentTarget; button.disabled = true; try { const response = await fetch(API, { method: 'POST', headers: { 'Content-Type': 'application/json', apikey: KEY }, body: JSON.stringify({ action: 'reset_routes', guild_id: id, view_scope: 'personal', access_token: token(), application_id: APP }) }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || 'Resetarea nu a reușit.'); button.textContent = '✅ Rutele au fost resetate'; render(card, await call(id)); } catch (error) { button.disabled = false; button.textContent = `⚠️ ${error.message}`; } };
    const actions = card.querySelector('.server-overview-actions');
    if (actions && !actions.querySelector('[data-reopen-onboarding]')) {
      const reopen = document.createElement('button');
      reopen.type = 'button'; reopen.className = 'button'; reopen.dataset.reopenOnboarding = 'true'; reopen.textContent = '📖 Reia tutorialul';
      actions.appendChild(reopen);
      reopen.onclick = () => { localStorage.removeItem(`panel-pro-onboarding-${id}`); panel.hidden = false; panel.scrollIntoView({ behavior: 'smooth', block: 'center' }); };
    }
    if (done === 6 && localStorage.getItem(`panel-pro-onboarding-${id}`) === 'hidden') panel.hidden = true;
  };
  const scan = () => document.querySelectorAll('#list .bot-card').forEach(async (card) => { if (card.dataset.guildId && card.dataset.onboarding !== 'loading') { card.dataset.onboarding = 'loading'; try { render(card, await call(card.dataset.guildId)); } catch (_) {} } });
  new MutationObserver(scan).observe(document.getElementById('list') || document.body, { childList: true, subtree: true });
  setInterval(scan, 1800); scan();
})();
