const DISCORD_PREMIUM_SKU_IDS = () => new Set(
  String(Deno.env.get('DISCORD_PREMIUM_GUILD_SKU_IDS') || Deno.env.get('DISCORD_PREMIUM_GUILD_SKU_ID') || '')
    .split(',')
    .map((value) => value.trim())
    .filter((value) => /^\d{15,22}$/.test(value)),
);

export function discordPremiumConfigured() {
  return DISCORD_PREMIUM_SKU_IDS().size > 0;
}

export function interactionHasDiscordGuildEntitlement(interaction: any, guildId: string) {
  const skuIds = DISCORD_PREMIUM_SKU_IDS();
  if (!skuIds.size) return false;
  const entitlements = Array.isArray(interaction?.entitlements) ? interaction.entitlements : [];
  return entitlements.some((entitlement: any) => {
    if (!skuIds.has(String(entitlement?.sku_id || '').trim())) return false;
    const entitlementGuildId = String(entitlement?.guild_id || '').trim();
    if (entitlementGuildId && entitlementGuildId !== String(guildId || '').trim()) return false;
    const endsAt = entitlement?.ends_at ? Date.parse(String(entitlement.ends_at)) : NaN;
    return !Number.isFinite(endsAt) || endsAt > Date.now();
  });
}

export async function discordPremiumAccess(db: any, organizationId: string, interaction: any, guildId: string) {
  if (interactionHasDiscordGuildEntitlement(interaction, guildId)) return true;
  // Discord interaction payloads do not include entitlements granted manually
  // by the platform administrator. Always check our persisted entitlement too.
  const [{ data: storedEntitlement, error: entitlementError }, { data, error }] = await Promise.all([
    db.from('discovery_guild_entitlements').select('ends_at').eq('guild_id', String(guildId || '').trim()).eq('organization_id', organizationId).eq('active', true).order('updated_at', { ascending: false }).limit(1).maybeSingle(),
    db.from('discovery_app_settings').select('value').eq('organization_id', organizationId).eq('key', 'discord_trial').maybeSingle(),
  ]);
  if (entitlementError) throw entitlementError;
  if (error) throw error;
  if (storedEntitlement && (!storedEntitlement.ends_at || Date.parse(String(storedEntitlement.ends_at)) > Date.now())) return true;
  const endsAt = Date.parse(String(data?.value?.ends_at || ''));
  return Number.isFinite(endsAt) && endsAt > Date.now();
}

export function discordPremiumModule(customIdOrRoute: string) {
  const value = String(customIdOrRoute || '').trim();
  // Singurele module gratuite sunt Pontaj și Învoiri angajați. Trial-ul este
  // un flux de activare, nu un modul Premium, deci rămâne accesibil tuturor.
  if (value === 'panel:discovery:trial_activate' || value === 'pontaj' || value === 'requests_departments' || value.startsWith('panel:pontaj:') || value.startsWith('panel:requests:departments:')) return false;
  return true;
}

export function discordPremiumButton(skuId = [...DISCORD_PREMIUM_SKU_IDS()][0] || '') {
  // Discord SKU buttons accept sku_id, but not label (the label is generated by Discord).
  return skuId ? [{ type: 1, components: [{ type: 2, style: 6, sku_id: skuId }] }] : [];
}

export function discordPremiumMessage(skuId = [...DISCORD_PREMIUM_SKU_IDS()][0] || '') {
  return {
    type: 4,
    data: {
      content: 'Acest server nu are un abonament Panel Pro Premium activ. Activează abonamentul pentru a folosi funcțiile botului Discord.',
      // Keep the entitlement prompt visible but silent in Discord clients.
      flags: 64 | 4096,
      components: discordPremiumButton(skuId),
    },
  };
}

export function discordPremiumSkuConfigured() {
  return DISCORD_PREMIUM_SKU_IDS().size > 0;
}
